M48
; DRILL file {KiCad (6.0.7)} date Sat Sep 10 12:27:57 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-10T12:27:57+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X96.355Y-93.5
X96.355Y-96.5
T2
X87.7Y-106.6
X92.3Y-106.6
T3
X90.0Y-54.5
T0
M30
